# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: lobbysvrd

redis:
  enable: true
  
type_id: 65
type_name: "lobbysvr"

image:
  repository: harbor.m-oa.com:6023/project-y/project-y-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
volumeMounts:
  mountPath: /service/lobbysvr/cfg
  
imagePullSecrets:
  - name: jijunliang-harbor-regcred

persistence:
  cbs:
    enabled: false
    volumes:
      - name: log
        storage: 50Gi
        mountPath: /service/lobbysvr/log

gateway:
  class: cilium
  port: 7001
  hostname: gateway.example.com
  addresses_ip: 127.0.0.1

httproute:
  port: 7001
  sectionName: http

service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP
