# Default values for lobby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proc_name: lobbysvrd

redis:
  enable: true
  
type_id: 65
type_name: "lobbysvr"

image:
  repository: harbor.m-oa.com:6023/project-y/project-y-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

volumeMounts:
  configMountPath: /service/lobbysvr/cfg
  logMountPath: /service/lobbysvr/log

vector:
  image:
    repository: harbor.m-oa.com:6023/vector/vector:latest
    pullPolicy: Always
  opensearch:
    username: project-Y-log-writer
    password: 11bo1B{OE,gjzZ4D
    endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200/

imagePullSecrets:
  - name: jijunliang-harbor-regcred

persistence:
  cbs:
    enabled: true
    storageClass: openebs-hostpath
    volumes:
      - name: log
        storage: 5Gi
        accessMode: ReadWriteOnce

gateway:
  class: cilium
  port: 7001
  hostname: gateway.example.com
  addresses_ip: 127.0.0.1

httproute:
  port: 7001
  parentRefsName: project-y-tls-gateway

service:
  type: ClusterIP
  port: 7001
  targetPort: 7001
  protocol: TCP
webserver:
  port: 7001

# websocket:
  # websocket 路径片段 实际路径为 /<deployment_environment>/daily/ws/v1
  # path: daily 
