{{- template "libapp.configmap" (list . "lobbysvr.configmap") -}}
{{- define "lobbysvr.configmap" -}}
data:
  {{ include "lobbysvr.name" . }}.yaml: {{ tpl (.Files.Get "cfg/lobbysvr.yaml.tpl") . | quote }}
  # {{ include "lobbysvr.name" . }}_tlog.xml: {{ tpl (.Files.Get "cfg/lobbysvr.xml.tpl") . | quote }}
{{- end -}}
