{{- template "libapp.configmap" (list . "lobbysvr.configmap") -}}
{{- define "lobbysvr.configmap" -}}
data:
  {{ include "lobbysvr.name" . }}.yaml: {{ tpl (.Files.Get "cfg/lobbysvr.yaml.tpl") . | quote }}
  vector.yaml: {{ tpl (.Files.Get "cfg/vector.yaml.tpl") . | quote }}
{{- end -}}
